### ISSUE TITLE
Can't catch error

### ISSUE THREAD

**Issue by phoenix741** [akre54/Backbone.Fetch#2]
Hi,

I try to use this in my project, but i have a problem :

When i use like this :

```
object.fetch(options).then(function () {
   ...
}).catch(function () {
  ...
});
```

catch (on error, ie: 401) is never called because, the line .then(options.success, options.error) process the error.
So the error is considered as managed and the method then is called instead of catch.

I think that we should call options.error in a method a re-trigger the the exception.

**Comment by phoenix741** [comment]
I have change to the following code:

```
        .then(options.success)
        .catch(function(e) {
            options.error(e);
            throw e;
        });
```

**Comment by akre54** [comment]
Go for it! Open a pull request with some tests and I'll add it in.

**Comment by skinnyjames** [comment]
Is fetch supposed to work this way?  per https://www.tjvantoll.com/2015/09/13/fetch-and-errors/
says that fetch should only throw on network errors.

I have an api that returns 422 errors with json, but I can't access the json from the promise result.
