### ISSUE TITLE
Uploading files and multipart data

### ISSUE THREAD

**Issue by skinnyjames** [akre54/Backbone.Fetch#9]
Very nice repo.  

When uploading files with FormData and a multipart content-type, I get the following error:
**Error: Multipart: Boundary not found**

Setting the content-type to undefined forces the browser to set the boundary and content type.

http://stackoverflow.com/questions/35795529/fetch-api-and-multer-error-while-uploading-file
http://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

I'm not sure if there is another way to manually set the content type to work with files, but removing the default content-type from the options allows for file uploads.

**Comment by akre54** [comment]
It should be possible to [override the `headers` object](https://github.com/akre54/Backbone.Fetch/blob/13e2138e8072e60d3231d7a81ed62bb2bec37feb/backbone.fetch.js#L43-L46) for those cases where you need to do something special. Let me know if that's not sufficient and we can reopen.

**Comment by skinnyjames** [comment]
That's sort of the issue.
By overriding the headers to have a content type of "multipart/form-data," the server errors that the multipart boundary can't be found.

This seems to be an issue with how fetch itself works, based on other's experiences.  The recommendation is to take the content-type out of the headers and let the browser generate it.  

It's interesting because when I set the content-type to undefined I expect the defaults function to override it with 'application/json', but it comes through as a string e.g. - "content-type": "undefined".  This might have to do with the way backbone's sync method works, but I still imagine that if the content-type header did come through as undefined, the defaults method would still override it.

Any ideas?

**Comment by akre54** [comment]
Unfortunately with the defaults function there's no nice way to *remove* a key, only [override it](https://github.com/akre54/Backbone.Fetch/blob/13e2138e8072e60d3231d7a81ed62bb2bec37feb/backbone.fetch.js#L12-L17). Maybe try with an empty string, or `null`?

It looks like `fetch` (or at least the fetch polyfill) has [its own logic](https://github.com/github/fetch/blob/b337f9578fa8e21fa5c9fe8d6eb74baaa43a1c02/fetch.js#L226-L234) for when the content-type header is falsey. (I think [this is the section](https://fetch.spec.whatwg.org/#concept-header-extract-mime-type) in the spec, so should work in native implementations too).

**Comment by skinnyjames** [comment]
Thanks for your help!

I tried the above.  I don't quite understand why falsey values are being quoted/literalized when I inspect the request object from node - using the fetch polyfill it correctly sets the content-type/boundary, but chrome v55 doesn't.  Fetch seems cool, but I think i'll just switch back to jQuery for now.

Thanks again

**Comment by akre54** [comment]
Sure, sorry to hear it.

Maybe as a last option, pass an `headers` object instead of trying to set the `content-type` directly? Should work. Otherwise if you can think of a good solution it might help the next person too.
